### PR TITLE
Version 0.9.2

### PR DESCRIPTION
**Pull request by aleksihakli**
I noticed that the current PyPI version has outdated package version specifiers and updating a new version to the PyPI repository could be a fairly small task :)

### CODE REVIEW

**Review by kencochrane — APPROVED** [review]
LGTM

**Review by hramezani — APPROVED** [review]

**Comment by aleksihakli** [comment]
This will need to be released through the Jazzband page automation at jazzband.co, wcan you do that @kencochrane? I do not have permissions for making new releases to PyPI.

**Comment by kencochrane** [comment]
Should be done. Thanks

**Comment by aleksihakli** [comment]
Seems like I missed the package specifier for Python 3.6. I rolled a release 0.9.3 that should be releasable through Jazzband.co again.

**Pull request merged**
