### PR TITLE
Changing order of defender urls in documentation and exampleapp/urls.py

### PR DESCRIPTION
**Pull request by dashgin**
if  `/admin/` comes before `/admin/defender/` then `/admin/defender/blocks/` url will give 404

### CODE REVIEW

**Comment by kencochrane** [comment]
It looks like some of the tests failed.

**Comment by dashgin** [comment]
How did tests failed? i just changed the url order

**Comment by kencochrane** [comment]
> How did tests failed? i just changed the url order

You changed more than that. You also changed strip_keys.

> AttributeError: 'str' object has no attribute 'removeprefix'

**Comment by dashgin** [comment]
Yes, actually I was going to open  a second pull request for `strip_keys` method. My bad, commits was confused.

Also, I have deleted my last commit, I will fixed:

> AttributeError: 'str' object has no attribute 'removeprefix'

 error and will commit it again

**Review by kencochrane — APPROVED** [review]
LGTM

**Pull request merged**
