### PR TITLE
Update Django and Python

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by hramezani** [comment]
@smithdc1 Could you please take a look?

**Comment by smithdc1** [comment]
@hramezani thanks for asking. 

- `install_requires` needs updating in `setup.py`. 
- should we drop python 3.5 (I think we should keep it, but Jazzband seems to be removing support). 
- one more inheritence from `object` in `defender/test.py`
- there's one warning that I can see locally. I think this one is on Django 3.1+?

`?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.
`

**Comment by hramezani** [comment]
@smithdc1 Thanks for the review.

> install_requires needs updating in setup.py.

Updated

> should we drop python 3.5 (I think we should keep it, but Jazzband seems to be removing support).

Yes, we should keep it but let's remove it like other Jazzband projects

> one more inheritence from object in defender/test.py

Removed.

> there's one warning that I can see locally. I think this one is on Django 3.1+?

Yes, it is on Django 3.1+. I adjusted to add the `"django.template.context_processors.request"` to `"context_processors"` on Django 3.1+

**Comment by smithdc1** [comment]
So many different places to update versions, tox.ini, setup.py, travis... I wish there was an easier way!

**Comment by smithdc1** [comment]
Hi Hasan, did you mean to push another commit here?

**Comment by hramezani** [comment]
@smithdc1 I addressed your comments. Did I miss something?

**Comment by smithdc1** [comment]
I can't see the `install_requires` or `context_processors` changes?

**Comment by hramezani** [comment]
Sorry. Forgot to push :man_facepalming:

**Review by smithdc1 — APPROVED** [review]

**Comment by smithdc1** [comment]
Thanks. Looks good to me. Assuming the confirms at some point....

**Comment by smithdc1** [comment]
oh my. Travis still hasn't run yet?

**Pull request merged**
